### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#11]
Hi ! 
-A- 
For the /modules/tag/view.tag.php (template tag_view.tpl)
How is the order ?
By descending date (newest first), regardless of the modules or groups per module?
Attention, there are 2 questions in this sentence lol

**Comment by mambax7** [comment]
Alphabetical

In the block, you can also have sorted by number of tags
![image](https://user-images.githubusercontent.com/613686/145678301-eb9f56e6-8101-4457-9875-d84584df4de6.png)

**Comment by alain01** [comment]
-B-
 I want this 
![Capture d’écran 2021-12-11 121145](https://user-images.githubusercontent.com/5336960/145678132-75d624e2-1076-43af-9605-25f7fc82f325.png)
to highlight the keyword found

The Idea is close to that : 

```
                <{foreach item=tag from=$tagbar.tags}>
                        <{if $tag == $tag_title}>
                            <li><{$tag|replace:"'>":"' > <span class=\"fa fa-tag text-warning\"></span> "}></li>
                        <{else}>
                            <li><{$tag|replace:"'>":"' > <span class=\"fa fa-tag"></span> "}></li>
                    <{/if}>
                <{/foreach}>
```

but  $tag is an url : 
 `<a href='http://xoops-tests2.local/modules/tag/view.tag.php/sport' title='sport' >`
and 
$tag_title is a a string of characters
`sport`

It's too hard for me with `|replace` or `|cat`...
Any solution ?

**Comment by alain01** [comment]
Quick answer ! 
For -A- 
No, I talk about the result, not the key/tag...

May be this
![Capture d’écran 2021-12-11 142951](https://user-images.githubusercontent.com/5336960/145678468-3a9a5c1c-27b5-40c5-a7fb-38626ba9b554.png)
 print screen could help for my question

**Comment by mambax7** [comment]
Talk to Heyula - he is good with templating, 
Other questions will need to wait till next week, as I have to focus on other things! Sorry!

**Comment by alain01** [comment]
ok no pb

**Comment by alain01** [comment]
With help from @GregMage: 
![Capture d’écran 2021-12-12 170721](https://user-images.githubusercontent.com/5336960/145719964-defbc25d-1905-4ef5-8c1a-1ee41d8823f6.png)

**Comment by mambax7** [comment]
That looks great! Can you close it now?

**Comment by alain01** [comment]
humm no,
the order is a problem.

If there is 20 contents (or more)  with the same tag (in this exemple, tag "sport")
we want to display the last contents, by descending date (newest first), regardless of the modules or groups per module.

**Comment by mambax7** [comment]
I'm brain dead now, so maybe in the next release...

**Comment by alain01** [comment]
Ok, ;-)))
I will open a new issue with just one subject : Order then I close this issue.

**Comment by alain01** [comment]
Let me test my new bt4 templates with your modifications before publish a beta version, please.
I need to test with multi-pages and with the default value in <{$tag_term|default:''}>.

**Comment by mambax7** [comment]
Too late :) 
We can make changes in Beta 5

**Comment by mambax7** [comment]
Please test all you templates on PHP 8+, as the Smarty default issues show up there

**Comment by alain01** [comment]
Humm, ok.
My tests are actually in 7.3

**Comment by mambax7** [comment]
The Smarty default issues don't show up till PHP 8, so you need to start testing ALL templates with PHP 8+
I'm actually testing everything on PHP 8.1, to make sure that everything works there.

**Comment by alain01** [comment]
I closed it to follow the unique subject here: https://github.com/mambax7/tag/issues/18
