### ISSUE TITLE
Error on the multi page : class/TagHandler.php line 483

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#12]
Error : TypeError: Return value of XoopsModules\Tag\TagHandler::getItemCount() must be of the type int, string returned

How to get this error : 

- Use a tag word in different content (ex : mountain"), in more than 3 contents.
- Go to the module prefernces and modify **Items per page** to 3
- then go to a content with the tag "mountain" and click on the tag "mountain" in this content
- /modules/tag/view.tag.php/mountain

=> Error: TypeError: Return value of XoopsModules/Tag/TagHandler::getItemCount() must be of the type int, string returned in file /modules/tag/class/TagHandler.php line 483

**Comment by mambax7** [comment]
This should fix it: https://github.com/mambax7/tag/commit/6c80c09ee2ba11dea2795eb34632cea4bf5a620e
Please reopen if this is still an issue

**Comment by alain01** [comment]
Ok Thank you Mamba.
I will test this evening or tomorrow.
It is possible that with a working pagination, I will slightly modify my bt4 templates.
