### ISSUE TITLE
Number of tags

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#13]
Preferences:
Limit number of items per list: 8
Limit number of items per cloud: 15

/modules/tag/   
13 tags (=15-2)

When I click on the "plus" link, 13 same tags (=15-2)

=========
When I set **Limit number of items per cloud** to 10
we get so 8 tags (=10-2)

========

And why **/modules/tag/** (index.php)  and  **/modules/tag/list.tag.php** display same tags (colos are different but same tags) and same number of tags ?

**Comment by mambax7** [comment]
This seems to be working now:

![image](https://user-images.githubusercontent.com/613686/146189028-27831192-82ac-44ef-ae2d-ff4e7d0718ab.png)
