### ISSUE TITLE
flash block

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#14]
We need to delete the flash bloc !

**Comment by mambax7** [comment]
it's commented out. I'm leaving it for the time being, in case somebody wants to rewrite it using Javascript.

**Comment by alain01** [comment]
Ok for that but I think the work is not complete.
We need to delete:
- https://github.com/mambax7/tag/blob/master/assets/cumulus.swf
- https://github.com/mambax7/tag/tree/master/assets/js (or just the swfobject.js file) (It's js to run with swf file)

**Comment by mambax7** [comment]
Done: https://github.com/mambax7/tag/commit/e5b4e48b6d37acb8da7e6cc094bbcbc412f76e14
