### ISSUE TITLE
bloc top and bloc cloud

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#15]
the paramaters in block admin are not read

### Top tag
**Number to display:** 
Try to change this parameter and ... nothing change
**Sort Criteria**
Same

### Tag cloud
**Number to display:** 
Try to change this parameter and ... nothing change

**Comment by mambax7** [comment]
Should be now fixed in https://github.com/mambax7/tag/commit/6fc3a657da832a46166dca71086cd887bbfb2771

This is how it looked in my test:

![image](https://user-images.githubusercontent.com/613686/146187827-967a7d77-b6db-4d65-a073-62e3ecb58d4b.png)

**Comment by alain01** [comment]
Please re-open... Dont close until I have tested it, please.
My first tests with php 7.3 for the moment.

**Block Tag cloud :** 
Number to display:
Display ok till 9 
1 => 1 is displayed
...
9 => 9
Then
10 => 9
11=>9
12 =>10
13=>11
14 =>12
15 => 12
16 => 13
17 => 14
18 => 15
19 => 16
etc
 

**Block Top Tag**
Sort Criteria: Ok now
Number to display:
1 =>1 is displayed
...
8 => 8
9 => 8
10 => 9
11 => 10
12 => 11
13 => 12
14 => 12
15 => 12
...
18 => 12

So Max 12 and pb after 8.

**Comment by mambax7** [comment]
You can always re-open yourself, that's not a problem!

**Comment by alain01** [comment]
ok ;-)

**Comment by mambax7** [comment]
Could not replicate it with Publisher. 
I tested with both 20, and then 10 (Cloud Block) and 15 (Top Tag Block):

![image](https://user-images.githubusercontent.com/613686/146367505-d9b4fb16-87a2-4bb9-bbc6-894bfbeda326.png)

**Comment by alain01** [comment]
Ok, I dont know... but i get the problem.
I will test without xmnews, just with publisher...

**Comment by alain01** [comment]
Ok Please REOPEN ! 

Please test with just 1 module, for example, publisher ! 
All is ok ! 
Then add xmenws, now we get these troubles

Now, desactivate publisher, update tag,
all is ok ok with xmnews (just xmnews)
Then add publisher, 
Now, we get the same problem

So, the problem is not publisher, the problem is not xmnews,
the problem appears when there is more than one module working with the tag module !

**Comment by mambax7** [comment]
You should be able to reopen it yourself, don't you? If there is a problem, please re-open!

**Comment by alain01** [comment]
I cant reopen,
I have just the "comment" button
![Capture d’écran 2021-12-20 162256](https://user-images.githubusercontent.com/5336960/146791051-f78de5d9-d68d-43d5-8ac4-338d194ac823.png)

**Comment by mambax7** [comment]
Hmm, that strange! OK, I'll reopen!

**Comment by mambax7** [comment]
Or you can open a new one :) 
But which one issues do we still have here? 

Is it this one? 

![image](https://user-images.githubusercontent.com/613686/146793371-5bae5d12-23f1-4b6e-8534-7f8c8a24c09d.png)

**Comment by alain01** [comment]
yes

**Comment by mambax7** [comment]
I hope, this will finally fix it :) 
https://github.com/mambax7/tag/commit/f07f7b291a4abf6ecd00e7414747b5765b3d679d

**Comment by alain01** [comment]
### Awesome !!!

It works now ! 
You delete 1 word in the PHP/Sql code and all is ok now ? !!! (, l.tag_modid)

**Bravo** et **merci** pour cette recherche et pour la **correction du bug**, Mamba.
Encore bravo !
