### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#18]
Hi
The order is a problem.

URL example: 
/modules/tag/view.tag.php/sport 

If there is 20 contents (or more) with the same tag (in this exemple, tag "sport")
we want to display the last contents, by descending date (newest first) and
![Capture d’écran 2021-12-17 093242](https://user-images.githubusercontent.com/5336960/146514356-a3e84a7c-3cd3-4db5-ad70-86ffbb248f2e.png)
 regardless of the modules or groups per module and not .

**Comment by mambax7** [comment]
Maybe in the next release, right now no time to do it....

**Comment by alain01** [comment]
Ok no worries,
I write it down so I don't forget ;-)

**Comment by mambax7** [comment]
please test the latest version and see if it works for you: https://github.com/mambax7/tag/commit/b2070613302e8be5c9067610ae24475eb964bfaa

**Comment by alain01** [comment]
Perfeccccccct !!! Thank you ! 
![Capture d’écran 2021-12-18 115202](https://user-images.githubusercontent.com/5336960/146638414-47764c32-7a44-4d9a-963a-315555a4c4d6.png)

 
I change the published date of an older article to today, and it is at the top on the list ! 
Order works fine ... with 1 module, here publisher.
Let me test with xmenws + publisher ;-)))))

**Comment by alain01** [comment]
With several modules:
![Capture d’écran 2021-12-18 115958](https://user-images.githubusercontent.com/5336960/146638651-0ded5520-1df1-4352-a230-87c8e02040d9.png)

And the multipage is ok: (here 5 per page)
![Capture d’écran 2021-12-18 120432](https://user-images.githubusercontent.com/5336960/146638730-674545c0-d883-4657-8fb9-0e089107e20a.png)

May be i Need to move up the paging block in the template...
But all is ok for this issue, Mamba !
Thank you !

**Comment by mambax7** [comment]
You're welcome! 
I think, next release will be RC-1 instead of Beta-5 :)

**Comment by alain01** [comment]
Ok,...
I'm working on a new enhancement on the templates...
