### ISSUE TITLE
Minimal version of PHP - This module requires PHP version 7.4+ (7.3.25 installed)

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#21]
Impossible d'installer tag. Erreur(s) :
Installation de Tag
Échec lors de l'exécution de xoops_module_pre_install_tag
This module requires PHP version 7.4+ (7.3.25 installed)

Ok, now I undertand my strange problem...
So it 's a big trouble cause XOOPS 2.5.10, max is php 7.3
and for XOOPS 2.5.11, min is is php 7.3, not 7.4.

**Comment by mambax7** [comment]
Go to Tag's xoops_version.php and change the 7.4 to 7.3:
```php
    'min_php'             => '7.4',
```

**Comment by mambax7** [comment]
And install for your tests **PHP 7.4.26**, **PHP 8.0.13** and **PHP 8.1**
You have all of them available on WampServer:
https://wampserver.aviatechno.net/

**Comment by mambax7** [comment]
change the install, it should be OK now
