### ISSUE TITLE
Module update : undefined constant

### ISSUE THREAD

**Issue by alain01** [mambax7/tag#22]
Hi
Yes i know, again with php7.3
lastest version of tag starting 2.35.0 Beta 5 (master)

Module update : 

ERRORS
--
Warning: Use of undefined constant _PRINT - assumed '_PRINT' (this will throw an Error in a future version of PHP) in file /modules/tag/config/icons.php line 14
Warning: Use of undefined constant _PRINT - assumed '_PRINT' (this will throw an Error in a future version of PHP) in file /modules/tag/config/icons.php line 14
Warning: Use of undefined constant _PDF - assumed '_PDF' (this will throw an Error in a future version of PHP) in file /modules/tag/config/icons.php line 15
Warning: Use of undefined constant _PDF - assumed '_PDF' (this will throw an Error in a future version of PHP) in file /modules/tag/config/icons.php line 15
Warning: Use of undefined constant _OFF - assumed '_OFF' (this will throw an Error in a future version of PHP) in file /modules/tag/config/icons.php line 17

**Comment by alain01** [comment]
and in the queries tab: 

in red color:

0.000167 - DELETE FROM tag_link WHERE tag_modid = 0 AND ( tag_itemid NOT IN ( SELECT DISTINCT itemid FROM publisher_items WHERE publisher_items.status = Published ) )Error number: 1054Error message: Unknown column 'Published' in 'where clause'

**Comment by mambax7** [comment]
1) _PRINT, _PDF, and _OFF are defined in XOOPS 2.5.11 - you need to download the latest code from GitHub and use that

2) I'm not sure about the DELETE notice - did you deactivate Publisher before the update?

**Comment by alain01** [comment]
1 . Ok ! 
2 . No, but all is ok, I' ve just notice that
